name: josiepy_ci

on:
  pull_request:
    branches: [master]

env:
  JUPYTER_PLATFORM_DIRS: 1

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  build:
    needs: pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Poetry installation
        run: |
          pip install poetry
          poetry install -E jupyter

      - name: Run flake8
        run: |
          poetry run flake8

      - name: Run tests
        run: |
          poetry run pygount --format cloc-xml -o loc.xml josie
          poetry run pytest
